name: Content Indexing Continuous Integration

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install indexing dependencies
        run: npm install

      - name: Run indexing
        run: node index.js
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
          WORKER_API_KEY: ${{ secrets.WORKER_API_KEY }}
