name: Content Removal

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Namespace to remove"
        required: true
        type: choice
        options:
          - bookeeping
          - extension
          - makereels
          - website

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install indexing dependencies
        run: npm install

      - name: Run removal
        run: node remove.js "${{ github.event.inputs.namespace }}"
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
          WORKER_API_KEY: ${{ secrets.WORKER_API_KEY }}
